all:
	echo "generate pre presentation files"
	npx @marp-team/marp-cli@latest ppt.md -o aid-thesis-pre-presentation.html
	npx @marp-team/marp-cli@latest ppt.md -o aid-thesis-pre-presentation.pdf --allow-local-files
